### PR TITLE
Allow user to specify version to unshare

### PR DESCRIPTION
**Pull request by david-crowder**
Added some simple logic to allow you to unshare a specific version of a cookbook instead of always unsharing a whole project.

### CODE REVIEW

**Comment by nellshamrell** [comment]
Thank you for this!  Give us some time to test it and discuss it a bit and I will let you know if/when we decide to merge it!

Background: Whether or not we should allow people to unshare specific versions of cookbooks from public Supermarket has been under discussion for sometime.  It was originally something I was against, because whenever a new version of a cookbook is uploaded to public Supermarket it is almost immediately copied by Berks.  My concern was that it would allow users who accidentally upload security credentials (which does happen from time to time) a false sense of security - if they unshared the cookbook version from Supermarket, they might not realize those credentials would still be in the cookbook version in Berks.  However...it seems like this feature is highly desired and I think there is a way to make it work.  We could include a warning whenever someone attempts to unshare a version of a cookbook on public Supermarket - warning them that if they are unsharing the version because of accidentally uploading security credentials, they must invalidate those.  Basically, this is still under discussion, but I'm leaning toward allowing people to unshare specific versions of cookbooks from public Supermarket with proper warnings.  So...I will get back to you soon after I discuss this with the team!

**Comment by david-crowder** [comment]
Sure thing. My specific use case is entirely tied up with managing an internal supermarket and I can see that there would be concerns around allowing individual released artifacts to be pulled (reminds me of the [gem yank command](http://guides.rubygems.org/command-reference/#gem-yank)). I just happened to see that the endpoint existed and figured it may be something more people would be interested in. Thanks for getting back to me, I'll keep an eye out for updates.

**Comment by dissonanz** [comment]
FYI the same can be achieved by specifying `#{cookbook}/versions/#{version}` as the argument to `unshare` without this patch.

`knife supermarket unshare mycookbook/versions/0.1.0`

**Comment by nellshamrell** [comment]
Thanks, @dissonanz!

Closing this issue to contain conversation in https://github.com/chef/supermarket/issues/954

**Comment by david-crowder** [comment]
Thanks @dissonanz and @nellshamrell. I'll watch that other discussion :)

**Pull request closed without merging**
